# This is a basic workflow to help get started to CSC Rahti deployment with GitHub Actions

name: Image Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: my-flask-app
        TAGS: v1 ${{ github.sha }}
      steps:
        - name: Checkout source
          uses: actions/checkout@v3

# Setup S2i and Build container image
        - name: Setup and Build
          id: build_image
          uses: redhat-actions/s2i-build@v2
          with:
            path_context: '.'
            # Builder image for a Python project
            builder_image: 'registry.fedoraproject.org/f35/python3'
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.TAGS }}
# Push Image to Quay registry
        - name: Push To Quay Action
          uses: redhat-actions/push-to-registry@v2
          if: >
            (github.event_name == 'push' || github.event_name == 'schedule') &&
            (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
          with:
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: quay.io/${{ secrets.QUAY_USERNAME }}
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_PASSWORD }}
 
