# This is a basic workflow to help get started to CSC Rahti deployment with GitHub Actions

name: Image Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: my-flask-app
        TAGS: v1 ${{ github.sha }}
      steps:
        - name: Checkout source
          uses: actions/checkout@v3

# Setup S2i and Build container image
        - name: Setup and Build
          id: build_image
          uses: redhat-actions/s2i-build@v2
          with:
            path_context: '.'
            # Builder image for a Python project
            builder_image: 'registry.fedoraproject.org/f35/python3'
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.TAGS }}
# Push Image to Quay registry
        - name: Push To Quay Action
          uses: redhat-actions/push-to-registry@v2
          if: >
            (github.event_name == 'push' || github.event_name == 'schedule') &&
            (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
          with:
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: quay.io/${{ secrets.QUAY_USERNAME }}
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_PASSWORD }}
    
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      APP_NAME: "course-flask-demo"
      
    steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        # URL to your OpenShift cluster.
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}

        # Authentication Token. 
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        insecure_skip_tls_verify: true
        # This method is more secure, if the certificate from Step 4 is available.
        # certificate_authority_data: ${{ secrets.CA_DATA }}

        # Optional - this sets your Kubernetes context's current namespace after logging in.
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Create and expose app
      run: |
        oc delete deployment --all
        oc delete routes --all
        oc delete services --all
        oc new-app --name ${{ env.APP_NAME }} --docker-image=quay.io/${{ secrets.QUAY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
      
  
  
