name: Build and Push Image
on: [workflow_dispatch]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        env:
          IMAGE_NAME: flask-app
          TAGS: v1 ${{ github.sha }}
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: "."
          # Builder image for a java project
          builder_image: "centos/python-38-centos7"
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: quay.io/${{ secrets.QUAY_USERNAME }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
